[versions]
activity-compose = "1.8.2"
androidx-junit = "1.1.5"
coil-compose = "2.5.0"
core-ktx = "1.12.0"
espresso-core = "3.5.1"
gson = "2.10"
hilt-navigation-compose = "1.0.0"
javax-inject = "1"
junit = "4.13.2"
leakcanary-android = "3.0-alpha-1"
library-base = "1.11.0"
lifecycle-runtime-ktx = "2.7.0"
navigation-compose = "2.7.6"
kotlin = "1.9.0"
agp = "8.2.2"
appcompat = "1.6.1"
material = "1.11.0"
retrofit = "2.9.0"
moshi = "1.14.0"
moshi-codegen = "1.14.0"
logging-interceptor = "4.12.0"

hilt = "2.49"
room-runtime = "2.6.1"
ui-text-google-fonts = "1.6.2"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-navigation-compose" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room-runtime" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room-runtime" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room-runtime" }
androidx-ui-text-google-fonts = { module = "androidx.compose.ui:ui-text-google-fonts", version.ref = "ui-text-google-fonts" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil-compose" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
javax-inject = { module = "javax.inject:javax.inject", version.ref = "javax-inject" }
junit = { module = "junit:junit", version.ref = "junit" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
leakcanary-android = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary-android" }
library-base = { module = "io.realm.kotlin:library-base", version.ref = "library-base" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

# Retofit
moshi-kotlin-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi-codegen" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "logging-interceptor" }
retrofit-core = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-convertor = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }
moshi-core = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "logging-interceptor" }

# Hilt
hilt-core = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }

androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle-runtime-ktx" }

[plugins]
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }

